### ISSUE TITLE
Not able to set pageNeighbours above 2.

### ISSUE THREAD

**Issue by bdevika** [gladchinda/build-react-pagination-demo#2]

**Comment by gladchinda** [comment]
Limiting the value of `pageNeighbours` to a maximum of 2 is an intentional implementation choice, since higher values may cause the pagination widget to become unnecessarily cluttered.

Here is a screenshot of the code snippet that enforces this:
<img width="587" alt="Screen Shot 2019-04-12 at 11 58 38" src="https://user-images.githubusercontent.com/898538/56032896-2d7a4a00-5d1b-11e9-9bcb-00b5cab70c90.png">

However, you can easily modify this limit to suit your need. Simply change the allowed maximum value of the `pageNeighbours` prop from `2` to any higher number of your choice.

**Comment by bdevika** [comment]
@gladchinda  , oh,!ok , Thank you, it helped a lot :)

**Comment by bdevika** [comment]
Hi, one query if props get updated then in pagination component it's
 not getting reflected why?
